#title: AVERtek # your name photo (or website title) here
logo1: "images/aquis logo-K18 a400.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="text-align: center;" markdown="1"><b>On Mobile: Press "AR" Button; To Video Press/Hold Camera Button; Then Share!</h1></b></a> 
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-00000000-0 
